### ISSUE TITLE
Why Player Stopped after Playing 3 or 4 Videos ?

### ISSUE THREAD

**Issue by Rammehar** [brownsoo/flutter_video_list_sample#1]
I am playing a list of videos, after successfully played 3 or 4 videos. player stopped with this message updated -----> isPlaying=false / isEndPlaying=true.

**Comment by brownsoo** [comment]
ok. I will check it.

**Comment by brownsoo** [comment]
I updated the source checks the end of a video playing. 
It is difficult to check the end using `video_player` plug-in. 

please try again.
@Rammehar

**Comment by Rammehar** [comment]
Thank You for your support I have updated code Its working fine now thanks. My Another request is please add time duration, and loading indicator while slides video

**Comment by brownsoo** [comment]
Good. I also gonna add the duration of clip. please check next commit.
