### ISSUE TITLE
Custom queue video player

### ISSUE THREAD

**Issue by akunumanarif** [brownsoo/flutter_video_list_sample#3]
Hey, how can i set a listener that the next video can't be played before the previous is finished. Let's say i have 4 videos and it's always to be play from the first and procedurally. When i click the third or second it pop a dialog that the prev index must be finished. And store that index into a var maybe so we can display value in progressindicator. Please help, thanks

**Comment by brownsoo** [comment]
@akunumanarif You should handle the playing index manually in your case. When  the item is clicked, check item index is bigger 1 than the playing index. 

Following that condition, you can show the dialogs.
