### ISSUE TITLE
player starts lagging heavily after playing for some time

### ISSUE THREAD

**Issue by 2shrestha22** [brownsoo/flutter_video_list_sample#4]
player starts lagging heavily after playing for some time. it looks like playing heavy game in low end pc, like fps drop.

**Comment by brownsoo** [comment]
You played in android device? please let me know the issue environment.
Also I want to know the video file information (file size, codec..)

I also check My sample codes has memory loss.

**Comment by 2shrestha22** [comment]
Yes it was in Android. playing video for more than 4 min it start lagging. But I combined your UI with other logic found in Stackoverflow in my player.

**Comment by 2shrestha22** [comment]
here is the link of video samples I used, I tested with second video from the list with title "The first Blender Open Movie from 2006"
https://gist.github.com/jsturgis/3b19447b304616f18657

**Comment by 2shrestha22** [comment]
here is the link which i combined to yours, - https://stackoverflow.com/questions/58955831/flutter-video-player-dispose

**Comment by brownsoo** [comment]
Did you resolve this issue? I have no time these days. I will check within a week.

**Comment by brownsoo** [comment]
I also tested the remote file - "Elephant Dream".
I found that there  are too many listener updating. I fixed this issue by blocking listener call in correctly.

Please check latest source. 
Thank you for report.
@2shrestha22
